### ISSUE TITLE
No way to hide face clothing items (Eye reflection, shadow, etc).

### ISSUE THREAD

**Issue by ArtworkJustBecause** [acidbubbles/vam-improved-pov#11]
At the moment we can only tell hair and head not to render, but if we had the ability to manually select certain clothing items not to render would be very useful. For example there are several clothing items that augment or change the eyes of a character making a huge difference. Right now they are visible no matter what when possessing or using the passenger plugin.

**Comment by acidbubbles** [comment]
Yep, it's in my list. I think all clothes have the same "Alpha" channel so it might be feasible, the challenge is to know which clothing to hide or not. I might go with a regular expression :D Same for pubes v.s. hair.

**Comment by acidbubbles** [comment]
For the record, it's in my list for the Embody plugin: https://github.com/acidbubbles/vam-embody
